(format t "Aw, it was so bad we had to censor the whole screen!!!")
(format t "A smorgasbord of showgirls and showboys are noticed loligagging nevertheless; one of them starts playing IceJJFish's On the Floor on their smartwatch, while a person interrupts that they're still showering and trying to listen to Lil B's RED FLAME mixtape.")
(format t "One of them screams as a robotic centipede with red eyes and large sharp mettalic antennae slithers past.")
(format t "A door opens showcasing people dressed in white and assorted bling, as they march in carrying an artifact of sorts.")
(format t "A black backgrounded computer beeps revealing green text instructing people.")
(format t "A lifeguard reading it runs to the shower for an allegedly drowned; a sumo wrestler takes the place proclaiming to wait until they have done finishing the section.")
(format t "Someone says this is how we do it; randomly some other exclaims oh my goodness that thing is so cute; a third says **** YOU DUDE, **** YOU; An anonymous one says: chill to the rigueur, killin' it, feelin' it, in the gang, on an urge; Next watch it here sweetcake. Last... that's the sugar baby.")
(format t "The computer's hardware starts failing due to water damage, stating you don't have to implement the program, you do have to implement the program.")
(format t "A portal opens to a city, in which humans in hydraulically-powered mechas thunder forth, speaking of a recent settled war treaty.")
(format t "One of them says do you really think you can quit this game think again, showing streams of information to annihilate their injured freewill.")
